-- =================================================================
-- cross_ketto_f_chokyo_time.sqlx
-- 説明: 血統(父)とタイムごとの成績集計
-- =================================================================

config {
  type: "table",
  description: "血統(父)とタイムごとの成績集計",
  columns: {
    ketto1_f_hanshoku_toroku_bango: "血統情報1 父 繁殖登録番号",
    ketto1_f_bamei: "血統情報1 父 馬名",
    chokyo_sei_lap_group: "競走成績出走馬データ 追い切り chokyo_courseが栗東坂または美南坂 書籍「調教タイムの読み方」ラップのグループ分け",
    chokyo_sei_check_time_wood_4f_5f_flag: "競走成績出走馬データ 追い切り ウッド全体好時計は「はい」 該当しない場合はnull",
    chokyo_sei_check_time_wood_1f_2f_flag: "競走成績出走馬データ 追い切り ウッド終い鋭伸は「はい」 該当しない場合はnull",
    total_tansho_haraimodoshi: "単勝払戻金合計",
    total_fukusho_haraimodoshi: "複勝払戻金合計",
    count_1chaku: "1着回数",
    count_2chaku: "2着回数",
    count_3chaku: "3着回数",
    count_4chaku_ika: "4着以下回数",
    count_total_races: "総レース数"
  }
}

SELECT
  ketto1_f_hanshoku_toroku_bango,
  ARRAY_AGG(ketto1_f_bamei ORDER BY hasso_date DESC LIMIT 1)[OFFSET(0)] AS ketto1_f_bamei,
  chokyo_sei_lap_group,
  chokyo_sei_check_time_wood_4f_5f_flag,
  chokyo_sei_check_time_wood_1f_2f_flag,
  SUM(tansho_haraimodoshi_num) AS total_tansho_haraimodoshi,
  SUM(fukusho_haraimodoshi_num) AS total_fukusho_haraimodoshi,
  COUNTIF(kakutei_chakujun_num = 1) AS count_1chaku,
  COUNTIF(kakutei_chakujun_num = 2) AS count_2chaku,
  COUNTIF(kakutei_chakujun_num = 3) AS count_3chaku,
  COUNTIF(kakutei_chakujun_num >= 4) AS count_4chaku_ika,
  COUNT(*) AS count_total_races
FROM
  ${ref("race_uma_detail_looker")}
WHERE
  ketto1_f_hanshoku_toroku_bango IS NOT NULL
  AND kakutei_chakujun_num >= 1
  AND hasso_date >= DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Tokyo'), INTERVAL 3 YEAR), YEAR)
  AND hasso_date < DATE_TRUNC(CURRENT_DATE('Asia/Tokyo'), YEAR)
GROUP BY
  ketto1_f_hanshoku_toroku_bango,
  chokyo_sei_lap_group,
  chokyo_sei_check_time_wood_4f_5f_flag,
  chokyo_sei_check_time_wood_1f_2f_flag
