-- =================================================================
-- cross_chokyoshi_chokyo_time.sqlx
-- 説明: 調教師とタイムごとの成績集計
-- =================================================================

config {
  type: "table",
  description: "調教師とタイムごとの成績集計",
  columns: {
    chokyoshi_code: "調教師コード",
    chokyoshimei: "調教師名",
    chokyo_sei_lap_group: "競走成績出走馬データ 追い切り chokyo_courseが栗東坂または美南坂 書籍「調教タイムの読み方」ラップのグループ分け",
    chokyo_sei_check_time_wood_4f_5f_flag: "競走成績出走馬データ 追い切り ウッド全体好時計は「はい」 該当しない場合はnull",
    chokyo_sei_check_time_wood_1f_2f_flag: "競走成績出走馬データ 追い切り ウッド終い鋭伸は「はい」 該当しない場合はnull",
    chokyo_sei_batsugun_flag: "競走成績出走馬データ 追い切り 調教追い切り抜群馬 該当する場合「はい」該当しない場合はnull",
    total_tansho_haraimodoshi: "単勝払戻金合計",
    total_fukusho_haraimodoshi: "複勝払戻金合計",
    count_1chaku: "1着回数",
    count_2chaku: "2着回数",
    count_3chaku: "3着回数",
    count_4chaku_ika: "4着以下回数",
    count_total_races: "総レース数"
  }
}

SELECT
  chokyoshi_code,
  ARRAY_AGG(chokyoshimei ORDER BY hasso_date DESC LIMIT 1)[OFFSET(0)] AS chokyoshimei,
  chokyo_sei_lap_group,
  chokyo_sei_check_time_wood_4f_5f_flag,
  chokyo_sei_check_time_wood_1f_2f_flag,
  chokyo_sei_batsugun_flag,
  SUM(tansho_haraimodoshi_num) AS total_tansho_haraimodoshi,
  SUM(fukusho_haraimodoshi_num) AS total_fukusho_haraimodoshi,
  COUNTIF(kakutei_chakujun_num = 1) AS count_1chaku,
  COUNTIF(kakutei_chakujun_num = 2) AS count_2chaku,
  COUNTIF(kakutei_chakujun_num = 3) AS count_3chaku,
  COUNTIF(kakutei_chakujun_num >= 4) AS count_4chaku_ika,
  COUNT(*) AS count_total_races
FROM
  ${ref("race_uma_detail_looker")}
WHERE
  chokyoshi_code IS NOT NULL
  AND kakutei_chakujun_num >= 1
  AND hasso_date >= DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Tokyo'), INTERVAL 3 YEAR), YEAR)
  AND hasso_date < DATE_TRUNC(CURRENT_DATE('Asia/Tokyo'), YEAR)
GROUP BY
  chokyoshi_code,
  chokyo_sei_lap_group,
  chokyo_sei_check_time_wood_4f_5f_flag,
  chokyo_sei_check_time_wood_1f_2f_flag,
  chokyo_sei_batsugun_flag
