-- =================================================================
-- race_uma_detail_looker.sqlx
-- 説明: race_umaテーブルとraceテーブルを結合し、馬毎のレース詳細情報を持つテーブルを作成する。(Looker Studio用)
-- =================================================================

config {
  type: "operations",
  hasOutput: true,
  dependencies: [ "race", "race_uma" ],
  description: "馬毎のレース情報(race_uma)とレース自体の情報(race)を結合した詳細テーブル。(Looker Studio用)",
  columns: race_uma_detail_looker.columns
}

CREATE OR REPLACE MATERIALIZED VIEW ${self()}
PARTITION BY schedule_date
OPTIONS (enable_refresh = true, refresh_interval_minutes = 30)
AS
${race_uma_detail_looker.query(ref)}
