-- =================================================================
-- schedule.sqlx
-- 説明: kol_den1から発走日に関する情報を抽出し、整形するテーブル。
-- =================================================================

config {
  type: "table",
  description: "KOLの出馬表データ(den1)を元に、発走日に関する情報を整形したマスターテーブル。",
  columns: {
    id: "発走日8文字 YYYYMMDD",
    year: "発走年 YYYY",
    month_day: "発走月日4文字 MMDD",
    period1_start: "発走日時 date型 YYYY:MM:DD 00:00:00",
    period2_end: "発走日時 date型 YYYY:MM:DD 23:59:59",
    modified: "データ更新日時",
    created: "データ作成日時"
  }
}

-- kol_den1テーブルから開催年月日を抽出し、各種日付形式に変換する
SELECT
  -- 発走日（YYYYMMDD）
  kaisai_nengappi AS id,
  -- 発走年（YYYY）
  SUBSTR(kaisai_nengappi, 1, 4) AS year,
  -- 発走月日（MMDD）
  SUBSTR(kaisai_nengappi, 5, 4) AS month_day,
  -- 期間開始日時（YYYY-MM-DD 00:00:00）
  DATETIME_ADD(PARSE_DATETIME('%Y%m%d %H:%M:%S', kaisai_nengappi || ' 00:00:00'), INTERVAL 9 HOUR) AS period1_start,
  -- 期間終了日時（YYYY-MM-DD 23:59:59）
  DATETIME_ADD(PARSE_DATETIME('%Y%m%d %H:%M:%S', kaisai_nengappi || ' 23:59:59'), INTERVAL 9 HOUR) AS period2_end,
  -- データ更新日時
  CURRENT_TIMESTAMP() AS modified,
  -- データ作成日時
  CURRENT_TIMESTAMP() AS created
FROM
  ${ref("kol_den1")}
WHERE
  kaisai_nengappi >= '20230101'
-- 発走日ごとにグループ化
GROUP BY
  id,
  year,
  month_day,
  period1_start,
  period2_end