-- =================================================================
-- schedule.sqlx
-- 説明: kol_den1から発走日に関する情報を抽出し、整形するテーブル。
-- =================================================================

config {
  type: "table",
  description: "KOLの出馬表データ(den1)を元に、発走日に関する情報を整形したマスターテーブル。",
  columns: {
    id: "発走日8文字 YYYYMMDD",
    year: "発走年 YYYY",
    month_day: "発走月日4文字 MMDD",
    period1_start: "発走日時 date型 YYYY:MM:DD 00:00:00",
    period1_start_utc: "発走日時(UTC) date型 YYYY:MM:DD 00:00:00",
    period2_end: "発走日時 date型 YYYY:MM:DD 23:59:59",
    period2_end_utc: "発走日時(UTC) date型 YYYY:MM:DD 23:59:59",
    main_race_names: "当日に開催されるメインレース名。カンマ区切りの文字列型。グレードが高い順に表示。(例)フェアリーステークス(GⅢ),淀短距離ステークス,架空のレース",
    keibajo_names: "当日に開催される競馬場名。カンマ区切りの文字列型。競馬場コード昇順で表示。(例)札幌,函館,中山",
    modified: "データ更新日時",
    created: "データ作成日時"
  },
  bigquery: {
    partitionBy: "DATE(period1_start)"
  }
}

WITH
  -- raceテーブルからオープン競走（00004）を取得し、日ごとにレース名を結合
  main_races AS (
    SELECT
      SUBSTR(race_code_kol, 1, 8) AS date_id,
      -- グレード順（NULLの場合は最後）にレース名を結合
      STRING_AGG(race_name, ',' ORDER BY COALESCE(grade_code, '9') ASC, race_code_kol ASC) AS main_race_names
    FROM
      ${ref("race")}
    WHERE
      kyoso_joken_kubun = '00004' -- オープン
      AND kyosomei_15moji IS NOT NULL
      AND kyosomei_15moji != ''
    GROUP BY
      date_id
  ),
  -- 日ごとに開催される競馬場を取得
  daily_keibajo AS (
    SELECT
      SUBSTR(race_code_kol, 1, 8) AS date_id,
      keibajo_code_jvd,
      keibajo_name
    FROM
      ${ref("race")}
    GROUP BY
      1, 2, 3
  ),
  -- 競馬場名をコード順に結合
  keibajo_metrics AS (
    SELECT
      date_id,
      STRING_AGG(keibajo_name, ',' ORDER BY keibajo_code_jvd) AS keibajo_names
    FROM
      daily_keibajo
    GROUP BY
      date_id
  )

-- kol_den1テーブルから開催年月日を抽出し、各種日付形式に変換する
SELECT
  -- 発走日（YYYYMMDD）
  d1.kaisai_nengappi AS id,
  -- 発走年（YYYY）
  SUBSTR(d1.kaisai_nengappi, 1, 4) AS year,
  -- 発走月日（MMDD）
  SUBSTR(d1.kaisai_nengappi, 5, 4) AS month_day,
  -- 期間開始日時（YYYY-MM-DD 00:00:00）
  DATETIME_ADD(PARSE_DATETIME('%Y%m%d %H:%M:%S', d1.kaisai_nengappi || ' 00:00:00'), INTERVAL 9 HOUR) AS period1_start,
  PARSE_DATETIME('%Y%m%d %H:%M:%S', d1.kaisai_nengappi || ' 00:00:00') AS period1_start_utc,
  -- 期間終了日時（YYYY-MM-DD 23:59:59）
  DATETIME_ADD(PARSE_DATETIME('%Y%m%d %H:%M:%S', d1.kaisai_nengappi || ' 23:59:59'), INTERVAL 9 HOUR) AS period2_end,
  PARSE_DATETIME('%Y%m%d %H:%M:%S', d1.kaisai_nengappi || ' 23:59:59') AS period2_end_utc,
  -- メインレース名リスト
  mr.main_race_names,
  -- 開催競馬場リスト
  km.keibajo_names,
  -- データ更新日時
  CURRENT_TIMESTAMP() AS modified,
  -- データ作成日時
  CURRENT_TIMESTAMP() AS created
FROM
  ${ref("kol_den1")} AS d1
LEFT JOIN
  main_races AS mr
ON
  d1.kaisai_nengappi = mr.date_id
LEFT JOIN
  keibajo_metrics AS km
ON
  d1.kaisai_nengappi = km.date_id
WHERE
  d1.kaisai_nengappi >= '20230101'
-- 発走日ごとにグループ化
GROUP BY
  id,
  year,
  month_day,
  period1_start,
  period1_start_utc,
  period2_end,
  period2_end_utc,
  main_race_names,
  keibajo_names