const columns = {
    // ID / コード
    race_code_uma_kol: "KOL仕様馬毎レースID",
    race_code_uma_kol_zensou: "前走のKOL仕様馬毎レースID",
    race_code_uma_jvd: "JRA-VAN仕様馬毎レースID",
    race_code_uma_jvd_zensou: "前走のJRA-VAN仕様馬毎レースID",
    race_code_kol: "KOL仕様レースID",
    race_code_jvd: "JRA-VAN仕様レースID",
    schedule_id: "発走日8文字 YYYYMMDD",
    schedule_date: "発走日0時0分 date型",
    keibajo_code_jvd: "JRA-VAN仕様競馬場コード",
    keibajo_code_kol: "KOL仕様競馬場コード",
    hasso_date: "発走日時",
    hasso_date_utc: "発走日時(UTC)",
    kaiji: "開催回次",
    nichiji: "開催日次",

    race_bango_num: "レース番号 整数型",
    waku_kubun: "枠番区分",
    wakuban: "枠番",
    umaban: "馬番 2桁",
    umaban_num: "馬番 整数型",
    // 馬情報
    bamei: "馬名",
    seibetsu_code: "性別コード",
    seibetsu_code_label: "性別 牡/牝/せん",

    barei_num: "馬齢 整数型",

    futan_juryo_float: "負担重量 小数点第一位まで",
    blinker_shiyo_kubun: "ブリンカー使用区分",
    blinker_shiyo_kubun_label: "ブリンカー使用 「はい」/該当しない場合はnull",
    blinker_shiyo_first_flag: "初ブリンカー(競走馬に初めてブリンカー着用)の場合は「はい」、該当しない場合はnull。取消・除外等の確定着順なしレースはカウントせず、確定着順1以上の実走のみを着用回数に含める",

    rating_float: "レイティング 小数点第一位まで",
    rating_rank: "レイティング順位。最高値が1位、同値は同じ順位で次をスキップ",
    // 馬主・血統
    banushimei: "馬主名",
    banushimei_ryakusho: "馬主名略称",
    ketto_toroku_bango_kol: "KOL仕様 血統登録番号(馬コード)",
    ketto1_f_hanshoku_toroku_bango: "血統情報 父 繁殖登録番号",
    ketto1_f_bamei: "血統情報 父 馬名",
    ketto2_m_hanshoku_toroku_bango: "血統情報 母 繁殖登録番号",
    ketto2_m_bamei: "血統情報 母 馬名",
    ketto5_mf_hanshoku_toroku_bango: "血統情報 母父 繁殖登録番号",
    ketto5_mf_bamei: "血統情報 母父 馬名",
    kyuyo_riyu: "休養理由",
    // 騎手
    kishumei: "騎手名",
    kishu_code: "騎手コード",
    kishu_tozai_shozoku_code: "騎手東西所属区分",
    kishu_tozai_shozoku_code_label: "騎手東西所属 西/東/招待",
    kishu_minarai_code: "騎手見習コード",
    kishu_minarai_code_label: "騎手見習",
    kishu_norikawari_kubun: "騎手乗り替わり区分",
    kishu_norikawari_kubun_label: "騎手乗り替わり 該当する場合「はい」該当しない場合はnull",
    kishu_tennori_flag: "テン乗り(騎手がこの馬に初めて騎乗)の場合は「はい」、該当しない場合はnull。取消・除外等の確定着順なしレースはカウントせず、確定着順1以上の実走のみを騎乗回数に含める",
    kishu_shozokubasho_code: "騎手所属場所コード",
    kishu_shozokubasho_code_label: "騎手所属場所",
    kishu_shozoku_chokyoshi_code: "騎手が所属する調教師コード",
    // 調教師
    chokyoshi_code: "調教師コード",
    chokyoshimei: "調教師名",
    chokyoshi_shozokubasho_code: "調教師所属場所コード",
    chokyoshi_shozokubasho_code_label: "調教師所属場所",
    chokyoshi_tracen_kubun: "調教師トレセン区分",
    chokyoshi_tracen_kubun_label: "調教師トレセン区分",
    // 調教 (den2/sei2由来)
    chokyo_den_oikiri_kijosha: "調教騎乗者",
    chokyo_den_oikiri_nengappi_date: "調教年月日",
    chokyo_den_oikiri_nengappi_label: "調教1～3追い切り 調教年月日 文字列 y年m月d日(曜日)",
    chokyo_den_oikiri_nengappi: "調教年月日(文字列)",
    chokyo_den_oikiri_basho: "調教場所",
    chokyo_den_oikiri_course: "調教コース",
    chokyo_den_oikiri_course_kubun: "調教コース区分",
    chokyo_den_oikiri_basho_course_label: "調教場所とコースを結合したラベル",
    chokyo_den_oikiri_babajotai: "調教馬場状態",
    chokyo_den_oikiri_hanro_pool_kaisu_int: "坂路またはプール:chokyo_6f それ以外:null",
    chokyo_den_oikiri_8f: "調教タイム 8F",
    chokyo_den_oikiri_8f_float: "調教タイム 8F (小数点)",
    chokyo_den_oikiri_7f: "調教タイム 7F",
    chokyo_den_oikiri_7f_float: "調教タイム 7F (小数点)",
    chokyo_den_oikiri_6f: "調教タイム 6F",
    chokyo_den_oikiri_6f_float: "調教タイム 6F (小数点)",
    chokyo_den_oikiri_5f_float: "調教タイム 5F (小数点)",
    chokyo_den_oikiri_4f_float: "調教タイム 4F (小数点)",
    chokyo_den_oikiri_3f_float: "調教タイム 3F (小数点)",

    chokyo_den_oikiri_2f_float: "調教タイム 2F推定値 (小数点)",

    chokyo_den_oikiri_1f_float: "調教タイム 1F (小数点)",
    chokyo_den_oikiri_lap_8f: "追い切り 8Fラップタイム 8f-7f",
    chokyo_den_oikiri_lap_7f: "追い切り 7Fラップタイム 7f-6f",
    chokyo_den_oikiri_lap_6f: "追い切り 6Fラップタイム 6f-5f",
    chokyo_den_oikiri_lap_5f: "追い切り 5Fラップタイム 4f-3f",
    chokyo_den_oikiri_lap_4f: "追い切り 4Fラップタイム 4f-3f",
    chokyo_den_oikiri_lap_3f: "追い切り 3Fラップタイム 3f-2f",
    chokyo_den_oikiri_lap_2f: "追い切り 2Fラップタイム 2f-1f",
    chokyo_den_oikiri_lap_group: "調教ラップグループ A1-B3",
    chokyo_den_oikiri_lap_group_zensou: "調教1～3追い切り 坂路ラップグループ 前走",
    // 印（Shirushi）カラム
    shirushi_shirushi_label: "予想印ラベル",
    shirushi_shirushi_num: "予想印数値",
    chokyo_den_oikiri_ichidori: "調教位置取り",
    chokyo_den_oikiri_ashiiro: "調教脚色",
    chokyo_den_oikiri_ashiiro_label: "調教脚色(ラベル)",
    chokyo_den_oikiri_yajirushi: "調教矢印",
    chokyo_den_oikiri_yajirushi_label: "調教矢印(ラベル)",
    chokyo_den_ichidori_furi_win_flag: "併せ馬が存在し、かつchokyo_ichidoriが6～9(大外周り)かつ併せ先着の場合「はい」該当しない場合はnull",
    chokyo_den_awase: "出馬表出走馬データ 調教併せ",
    chokyo_den_awase_uma_bamei: "出馬表出走馬データ 調教併せ 馬名",
    chokyo_den_awase_uma_class: "出馬表出走馬データ 調教併せ馬 併せ当時のkyoso_joken_kubun_labelをもとに対応",
    chokyo_den_awase_uma_kaku_kubun: "出馬表出走馬データ 調教併せ馬 併せ当時の馬のクラスとの比較区分 格上/同格/格下",
    chokyo_den_awase_uma_kakuue_win_flag: "出馬表出走馬データ 調教併せ馬 格上に対して先着した場合は「はい」該当しない場合はnull",
    chokyo_den_awase_uma_this_week_race_code_uma_jvd: "出馬表出走馬データ 調教併せ馬 今週出走する場合のrace_code_uma_jvd（土曜開催：当日または翌日、日曜開催：当日または前日）今週出走しない場合はnull",
    chokyo_den_awase_time_sa_float: "出馬表出走馬データ 調教併せのテキストからタイム差を抽出(「秒」は除く)",
    chokyo_den_awase_kubun: "出馬表出走馬データ 調教併せ区分",
    chokyo_den_awase_flag: "出馬表出走馬データ 調教併せフラグ",
    chokyo_den_awase_flag_label: "出馬表出走馬データ chokyo_awase_flagをもとに対応 調教2の併せ/調教3の併せ",
    chokyo_den_tanpyo: "出馬表出走馬データ ブックによる調教短評",

    chokyo_den_oikiri_reigai: "調教例外",
    chokyo_den_oikiri_kijosha_kubun: "調教1～3追い切り 調教騎乗者区分",
    chokyo_den_oikiri_kijosha_equal_kishumei_flag: "調教1～3追い切り 調教騎乗騎手がレースでも騎乗する場合「はい」該当しない場合はnull",
    // スピード指数・ローテーション
    // 調教 (sei2由来)
    chokyo_sei_kijosha: "競走成績出走馬データ  追い切り 調教騎乗者",
    chokyo_sei_kijosha_kubun: "競走成績出走馬データ  追い切り 調教騎乗者区分",
    chokyo_sei_kijosha_equal_kishumei_flag: "競走成績出走馬データ  追い切り 調教騎乗騎手がレースでも騎乗フラグ",
    chokyo_sei_nengappi: "競走成績出走馬データ  追い切り 調教年月日",
    chokyo_sei_nengappi_label: "競走成績出走馬データ  追い切り 調教年月日 文字列 y年m月d日(曜日)",
    chokyo_sei_nengappi_date: "競走成績出走馬データ  追い切り 調教年月日 date形式",
    chokyo_sei_basho: "競走成績出走馬データ  追い切り 調教場所 (例)栗東/美南/美北/函館/笠松/プール",
    chokyo_sei_course: "競走成績出走馬データ  追い切り 調教コース (例)A/B/C/CW/D/E/本/内/芝/ダ/障/牧/坂/W/DW/外",
    chokyo_sei_course_kubun: "競走成績出走馬データ  追い切り 調教コース区分",
    chokyo_sei_basho_course_label: "競走成績出走馬データ  追い切り 調教場所とコースを結合したラベル (例)栗東坂",
    chokyo_sei_basho_course_label_zensou: "競走成績出走馬データ  追い切り 調教場所コース 前走",
    chokyo_sei_babajotai: "競走成績出走馬データ  追い切り 調教馬場状態 良/重/不/稍",
    chokyo_sei_hanro_pool_kaisu_int: "競走成績出走馬データ  追い切り 坂路またはプール:chokyo_6f それ以外:null (例)1",
    chokyo_sei_8f: "競走成績出走馬データ  追い切り 調教タイム 8F",
    chokyo_sei_8f_float: "競走成績出走馬データ  追い切り chokyo_8f 小数点第一位まで",
    chokyo_sei_7f: "競走成績出走馬データ  追い切り 調教タイム 7F",
    chokyo_sei_7f_float: "競走成績出走馬データ  追い切り chokyo_7f 小数点第一位まで",
    chokyo_sei_6f: "競走成績出走馬データ  追い切り 調教タイム 6F",
    chokyo_sei_6f_float: "競走成績出走馬データ  追い切り chokyo_6f 小数点第一位まで",

    chokyo_sei_5f_float: "競走成績出走馬データ  追い切り chokyo_5f 小数点第一位まで",

    chokyo_sei_4f_float: "競走成績出走馬データ  追い切り chokyo_4f 小数点第一位まで",

    chokyo_sei_3f_float: "競走成績出走馬データ  追い切り chokyo_3f 小数点第一位まで",
    chokyo_sei_2f_float: "競走成績出走馬データ  追い切り 調教タイム 2F推定値 (小数点)",

    chokyo_sei_1f_float: "競走成績出走馬データ  追い切り chokyo_1f 小数点第一位まで",
    chokyo_sei_lap_8f: "競走成績出走馬データ  追い切り 8Fラップタイム 8f-7f",
    chokyo_sei_lap_7f: "競走成績出走馬データ  追い切り 7Fラップタイム 7f-6f",
    chokyo_sei_lap_6f: "競走成績出走馬データ  追い切り 6Fラップタイム 6f-5f",
    chokyo_sei_lap_5f: "競走成績出走馬データ  追い切り 5Fラップタイム 5f-4f",
    chokyo_sei_lap_4f: "競走成績出走馬データ  追い切り 4Fラップタイム 4f-3f",
    chokyo_sei_lap_3f: "競走成績出走馬データ  追い切り 3Fラップタイム 3f-2f",
    chokyo_sei_lap_2f: "競走成績出走馬データ  追い切り 2Fラップタイム 2f-1f",
    chokyo_sei_lap_group: "競走成績出走馬データ  追い切り ラップグループ A1-B3",
    chokyo_sei_lap_group_zensou: "前走の坂路ラップグループ",
    chokyo_sei_ichidori: "競走成績出走馬データ  追い切り 調教位置取り",

    chokyo_sei_ashiiro: "競走成績出走馬データ  追い切り 調教脚色",
    chokyo_sei_ashiiro_label: "競走成績出走馬データ  追い切り 調教脚色(ラベル)",
    chokyo_sei_yajirushi: "競走成績出走馬データ  追い切り 調教矢印",
    chokyo_sei_yajirushi_label: "競走成績出走馬データ  追い切り 調教矢印(ラベル)",
    chokyo_sei_reigai: "競走成績出走馬データ  追い切り 調教例外",
    chokyo_sei_naka1week_fight_flag: "競走成績出走馬データ  追い切り 中1週勝負パターン",



    zensou_kankaku: "前走との間隔。実際の日数差をもとに判定 連闘/中1週/中2週/中3週/.../中14週/中15週以上/初出走",
    zensou_kankaku_num: "前走との間隔を整数で表現。初出走:0、連闘:1、中1週:2、中N週:N+1",
    // 馬体重・前走比較
    bataiju: "馬体重(kg)",
    bataiju_zensou: "前走 馬体重kg",
    kyori_kubun_zensou: "前走 距離区分",
    kyori_zensou: "距離 前走",
    kishu_code_zensou: "騎手コード 前走",
    kishumei_zensou: "騎手名 前走",
    chokyo_sei_check_time_wood_4f_5f_flag_zensou: "ウッド全体好時計判定 前走",
    chokyo_sei_check_time_wood_1f_2f_flag_zensou: "ウッド終い鋭伸判定 前走",
    chokyo_den_oikiri_check_time_wood_4f_5f_flag_zensou: "調教1～3追い切り ウッド全体好時計判定 前走",
    chokyo_den_oikiri_check_time_wood_1f_2f_flag_zensou: "調教1～3追い切り ウッド終い鋭伸判定 前走",
    kakutei_tansho_ninkijun_num_zensou: "単勝 人気順 前走",
    corner3_juni_label_zensou: "3角順位 前走",
    corner3_juni_furi_zensou: "3角における不利情報 前走",
    corner4_juni_label_zensou: "4角順位 前走",
    corner4_juni_furi_zensou: "4角における不利情報 前走",
    corner4_ichidori_label_zensou: "4角位置取り 前走",
    kyori_extension_flag: "距離延長フラグ",
    kyori_shortening_flag: "距離短縮フラグ",
    ensei_kansai_to_kantou_flag: "遠征 関西→関東",
    ensei_kantou_to_kansai_flag: "遠征 関東→関西",
    track_code1_label_dirtsiba_zensou: "前走 ダ/芝",
    siba_to_dirt_flag: "芝→ダ替わりフラグ",
    dirt_to_siba_flag: "ダ→芝替わりフラグ",
    // 成績 (sei2)


    zogen_sa_num: "増減差(整数)",

    kakutei_chakujun_num: "確定着順(整数)",
    kakutei_chakujun_num_zensou: "前走 確定着順 整数型",

    tansho_haraimodoshi_num: "単勝払戻(整数)",

    fukusho_haraimodoshi_num: "複勝払戻(整数)",
    ijo_kubun_code1: "異常区分コード1",
    ijo_kubun_code1_label: "異常区分コード1(ラベル)",
    ijo_kubun_code2: "異常区分コード2",
    ijo_kubun_code2_label: "異常区分コード2(ラベル)",
    nyusen_juni: "入線順位",
    nyusen_juni_num: "入線順位(整数)",


    soha_time_float: "走破タイム(秒換算)",
    soha_time_label: "走破タイム(xx分xx.x秒)",

    chakusa_code1_num: "着差コード1(整数)",
    chakusa_code2: "着差コード2",
    chakusa_code2_label: "着差コード2(ラベル)",
    chakusa_label: "着差(ラベル)",

    time_sa_float: "タイム差(小数点)",

    zenhan_3f_float: "前半3F(小数点)",

    kohan_3f_float: "後半3F(小数点)",
    corner1_juni: "1角順位",
    corner1_juni_label: "corner1_juniをもとに対応 01〜28 40以上の場合は40を差し引く",
    corner1_juni_furi: "corner1_juniをもとに対応 31:落馬 32:中止 40以上:不利",
    corner2_juni: "2角順位",
    corner2_juni_label: "corner2_juniをもとに対応 01〜28 40以上の場合は40を差し引く",
    corner2_juni_furi: "corner2_juniをもとに対応 31:落馬 32:中止 40以上:不利",
    corner3_juni: "3角順位",
    corner3_juni_label: "corner3_juniをもとに対応 01〜28 40以上の場合は40を差し引く",
    corner3_juni_furi: "corner3_juniをもとに対応 31:落馬 32:中止 40以上:不利",
    corner4_juni: "4角順位",
    corner4_juni_label: "corner4_juniをもとに対応 01〜28 40以上の場合は40を差し引く",
    corner4_juni_furi: "corner4_juniをもとに対応 31:落馬 32:中止 40以上:不利",
    corner4_ichidori: "4角位置取り",
    corner4_ichidori_label: "4角位置取り(ラベル)",
    comment_kishu_kyusha: "騎手・厩舎コメント",
    comment_next: "次走コメント",
    comment_last: "前走コメント",
    yosou_tansho_ninkijun_num: "予想単勝人気順(数値)",
    yosou_tansho_odds_float: "予想単勝オッズ(数値)",
    yosou_tansho_odds_kubun: "予想単勝オッズ区分",
    kakutei_tansho_ninkijun_num: "確定 単勝 人気順 整数型",
    kakutei_tansho_odds_float: "確定 単勝 オッズ 小数点第一位まで",

    // 展開予想
    tenkai_kyakushitsu_kubun: "展開予想 脚質 逃げ/先行/差し/追い込み",
    tenkai_position: "展開予想 脚質内の順番。一団時は全員同値 1～4",
    tenkai_ittai_flag: "展開予想 一団フラグ。該当する場合「はい」該当しない場合はnull",
    tenkai_order: "展開予想 全体通し順位。一団時は同値になる。1～28",

    // --- raceテーブル由来のカラム ---
    race_name: "レース名。オープン競走では競走名とグレード、それ以外では条件を組み合わせて生成",
    kyori_kubun: "短距離(～1399m)/マイル(1400m～1699m)/中距離(1700m～2099m)/長距離(2100m～)",
    keibajo_name: "札幌/函館/福島/新潟/東京/中山/中京/京都/阪神/小倉",
    chuo_chiho_kubun: "中央･地方･外国 区分",
    chuo_chiho_kubun_label: "chuo_chiho_kubunをもとに対応 中央/南関東/その他の公営/道営/外国",
    kyosomei_15moji: "競走名15文字",
    kyosomei_7moji: "競走名7文字",
    grade_code: "グレードコード",
    grade_code_label: "grade_codeをもとに対応 GⅠ/GⅡ/GⅢ/JGⅠ/JGⅡ/JGⅢ",
    jpn_flag: "Jpnフラグ",
    jpn_flag_label: "grade_codeの有無をもとに対応 国際格付けレース（G）/それ以外の重賞（Jpn）",
    bettei_barei_handicap_summary_code: "重量種別コード(別定馬齢ハンデ概要コード)",
    bettei_barei_handicap_summary_code_label: "bettei_barei_handicap_summary_codeをもとに対応 別定/馬齢/ハンデ/定量/規定(道営のみ)/重量区分なし",
    bettei_barei_handicap_detail: "別定/馬齢/ハンデ/定量/規定（道営のみ）/牡 55 K/牝 53 K/牝2K減",
    kyoso_joken_age_limit: "競走種別コード2 条件年齢制限",
    kyoso_joken_age_limit_label: "kyoso_joken_age_limitをもとに対応 2歳/3歳/4歳/3,4,5歳/4,5,6歳/3歳以上/4歳以上/3,4歳/4,5歳",
    kyoso_joken_kubun: "競走条件コード1 競走条件区分",
    kyoso_joken_kubun_label: "kyoso_joken_kubunをもとに対応 新馬/未出走/未勝利/1勝クラス/2勝クラス/3勝クラス/オープン",
    kyoso_hiraba_tokubetsu_kubun: "kyosomei_15mojiに値がある場合は特別、そうでない場合は平場",
    heichi_shogai_kubun: "平地･障害 区分",
    heichi_shogai_kubun_label: "heichi_shogai_kubunをもとに対応 平地/障害",
    track_code1_dirtsiba: "トラックコード ダ･芝",
    track_code1_dirtsiba_label: "track_code1をもとに対応 ダ/芝",
    track_code2_LRS: "トラックコード 右･左",
    track_code2_LRS_label: "track_code2をもとに対応 右/左/直線",
    track_code3_inout: "トラックコード 内･外",
    track_code3_inout_label: "track_code3をもとに対応 内/外/外→内/タスキ/大障害/内２週/内→外",
    course_kubun: "コース区分",
    course_kubun_label: "course_kubunをもとに対応 A/B/C/D/A1/A2/E",
    kyori: "距離",
    toroku_tosu_num: "登録頭数 整数型",
    torikeshi_tosu_num: "取消頭数 整数型",
    tenko_code: "天候コード",
    tenko_code_label: "天候コードラベル (晴, 曇, 雨...)",
    babajotai_code: "馬場状態コード",
    babajotai_code_label: "馬場状態ラベル (良, 稍, 重, 不良)",
    pace_yosou: "ペース(予想)",
    pace_yosou_label: "ペース(予想) ラベル (H, M, S)",
    pace_kekka: "ペース(結果)",
    pace_kekka_label: "ペース(結果) ラベル (H, M, S)",
    race_tanpyo: "レース短評",
    juryo_handicap_flag: "重量種別が別定または馬齢の場合に「はい」",
    keibajo_komawari_curve4_flag: "競馬場が札幌/函館/福島/小倉かつ距離が1700m以上の場合に「はい」",
    keibajo_omawari_curve4_flag: "指定された競馬場、トラック、距離の組み合わせ条件を満たす場合に「はい」",
    keibajo_straight_short_flag: "指定された競馬場、トラックの組み合わせ条件を満たす場合に「はい」",
    keibajo_straight_long_flag: "東京芝、阪神芝外回り、新潟芝外回りの場合に「はい」",
    // --- タイムスタンプ ---
    created: "データ作成日時",
    modified: "データ更新日時"
};

const query = (ref) => `
SELECT
  ru.*,
  r.* EXCEPT (
    -- race_umaと重複するカラムをraceテーブルから除外
    race_code_kol, race_code_jvd, hasso_date, hasso_date_utc, kaiji, nichiji, race_bango_num,
    keibajo_code_jvd, keibajo_code_kol, created, modified, schedule_id, schedule_date
  )
FROM
  ${ref("race_uma")} AS ru
  LEFT JOIN ${ref("race")} AS r
  ON ru.race_code_jvd = r.race_code_jvd
`;

module.exports = {
  columns,
  query
};
